#nullable enable
using GodotOpenMcp.Bridge.Editor;
using Xunit;

namespace GodotOpenMcp.Bridge.Tests
{
    /// <summary>
    /// Per-project deterministic port resolution tests for P1.4. Pins the hash formula + override
    /// precedence so it can never silently drift from the MCP server's mirror
    /// (<c>mcp-server/src/instance-discovery.ts</c>). Cross-side consistency is the whole point: the
    /// bridge and the MCP server compute the same port for the same project path with zero shared
    /// config.
    ///
    /// <para>
    /// If any constant here changes, update the matching test in
    /// <c>mcp-server/src/instance-discovery.test.ts</c> in the same task. Adapted from Unity's
    /// <c>InstancePortResolverTests</c>; the formula and pinned values are byte-identical.
    /// </para>
    /// </summary>
    public static class InstancePortResolverTests
    {
        const string SamplePath = "/Users/foo/MyGame";
        const string SamplePathAlt = "/some/path";

        // Pinned cross-side values. Both sides MUST agree:
        //   /Users/foo/MyGame → port 22028, hash prefix dca5061f6f21537c
        //   /some/path        → port 29602, hash prefix eda6cf0b63f1a1d2
        // Generated by the same 8-byte-prefix SHA256 formula on both sides.
        const int SamplePathExpectedPort = 22028;
        const string SamplePathExpectedHashPrefix = "dca5061f6f21537c";
        const int SamplePathAltExpectedPort = 29602;

        // ----- hash + port formula -----

        [Fact]
        public static void ProjectHash_IsStableAcrossCalls()
        {
            var a = InstancePortResolver.ProjectHash(SamplePath);
            var b = InstancePortResolver.ProjectHash(SamplePath);
            Assert.Equal(a, b);
        }

        [Fact]
        public static void ProjectHash_IsLowercaseHexSha256()
        {
            var hash = InstancePortResolver.ProjectHash(SamplePath);
            Assert.Equal(64, hash.Length);
            Assert.Equal(SamplePathExpectedHashPrefix, hash.Substring(0, 16));
            foreach (var c in hash)
                Assert.True((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f'),
                    $"Hash must be lowercase hex, got '{c}'");
        }

        [Fact]
        public static void ProjectHash_DifferentPaths_DifferentHashes()
        {
            var a = InstancePortResolver.ProjectHash(SamplePath);
            var b = InstancePortResolver.ProjectHash(SamplePathAlt);
            Assert.NotEqual(a, b);
        }

        [Fact]
        public static void ProjectHash_NormalizesBackslashesAndTrailingSlash()
        {
            var forward = InstancePortResolver.ProjectHash("/Users/foo/MyGame");
            var back = InstancePortResolver.ProjectHash("\\Users\\foo\\MyGame");
            var trailing = InstancePortResolver.ProjectHash("/Users/foo/MyGame/");
            Assert.Equal(forward, back);
            Assert.Equal(forward, trailing);
        }

        [Fact]
        public static void ComputePort_IsWithinRange()
        {
            var port = InstancePortResolver.ComputePort(SamplePath);
            Assert.InRange(port,
                InstancePortResolver.PortRangeStart,
                InstancePortResolver.PortRangeStart + InstancePortResolver.PortRangeSize - 1);
        }

        [Fact]
        public static void ComputePort_MatchesPinnedCrossSideValue()
        {
            // If this breaks, the MCP server's mirror in instance-discovery.ts has drifted from the
            // bridge. Update both sides together.
            Assert.Equal(SamplePathExpectedPort, InstancePortResolver.ComputePort(SamplePath));
            Assert.Equal(SamplePathAltExpectedPort, InstancePortResolver.ComputePort(SamplePathAlt));
        }

        [Fact]
        public static void ComputePort_DifferentPaths_LikelyDifferentPorts()
        {
            // Distinct paths almost always map to distinct ports; we only assert that the two pinned
            // paths differ (collisions on a 10000-port range are rare but possible in theory).
            Assert.NotEqual(
                InstancePortResolver.ComputePort(SamplePath),
                InstancePortResolver.ComputePort(SamplePathAlt));
        }

        // ----- override precedence -----

        [Fact]
        public static void ResolvePort_EnvOverrideWins()
        {
            var port = InstancePortResolver.ResolvePort(SamplePath, envPort: 19120);
            Assert.Equal(19120, port);
        }

        [Fact]
        public static void ResolvePort_FallsBackToHash_WhenNoOverride()
        {
            var port = InstancePortResolver.ResolvePort(SamplePath, envPort: null);
            Assert.Equal(SamplePathExpectedPort, port);
        }

        [Fact]
        public static void ResolvePort_InvalidOverride_FallsBackToHash()
        {
            // Out-of-range values are rejected, not trusted.
            Assert.Equal(SamplePathExpectedPort,
                InstancePortResolver.ResolvePort(SamplePath, envPort: 0));
            Assert.Equal(SamplePathExpectedPort,
                InstancePortResolver.ResolvePort(SamplePath, envPort: 70000));
        }

        [Fact]
        public static void ResolvePort_ValidOverrideAtBoundaries()
        {
            Assert.Equal(1, InstancePortResolver.ResolvePort(SamplePath, envPort: 1));
            Assert.Equal(65535, InstancePortResolver.ResolvePort(SamplePath, envPort: 65535));
        }

        [Fact]
        public static void IsValidPort_OnlyWithinTcpRange()
        {
            Assert.False(InstancePortResolver.IsValidPort(0));
            Assert.False(InstancePortResolver.IsValidPort(-1));
            Assert.False(InstancePortResolver.IsValidPort(65536));
            Assert.True(InstancePortResolver.IsValidPort(1));
            Assert.True(InstancePortResolver.IsValidPort(65535));
            Assert.True(InstancePortResolver.IsValidPort(22028));
        }

        // ----- paths -----

        [Fact]
        public static void LockPath_EndsWithProjectHashJson()
        {
            var path = InstancePortResolver.LockPath(SamplePath);
            var expectedSuffix = InstancePortResolver.ProjectHash(SamplePath) + ".json";
            Assert.EndsWith(expectedSuffix, path);
            Assert.Contains(".godot-open-mcp/instances/", path.Replace('\\', '/'));
        }

        [Fact]
        public static void LockPath_StableForSameProject()
        {
            var a = InstancePortResolver.LockPath(SamplePath);
            var b = InstancePortResolver.LockPath(SamplePath);
            Assert.Equal(a, b);
        }

        [Fact]
        public static void NormalizePath_ForwardSlashAndNoTrailingSlash()
        {
            Assert.Equal("/Users/foo/MyGame", InstancePortResolver.NormalizePath("/Users/foo/MyGame"));
            Assert.Equal("/Users/foo/MyGame", InstancePortResolver.NormalizePath("/Users/foo/MyGame/"));
            Assert.Equal("/Users/foo/MyGame", InstancePortResolver.NormalizePath("\\Users\\foo\\MyGame"));
            // Multiple trailing slashes collapse.
            Assert.Equal("/p", InstancePortResolver.NormalizePath("/p//"));
            // Root path "/" is preserved (length-1 guard).
            Assert.Equal("/", InstancePortResolver.NormalizePath("/"));
            // Empty input returns empty.
            Assert.Equal("", InstancePortResolver.NormalizePath(""));
        }
    }
}
